### ISSUE TITLE
Native Code required?

### ISSUE THREAD

**Issue by tiltmaster** [hamzasidd3634/camera_filter#11]
Hi,

I have been facing an issue when adding Camera_filters, do I need to implement and add native code? since adding any text and or filters results in an error of unable to find writeVideofile Method.

Please let me know if so

**Comment by hamzasidd3634** [comment]
can you specify the error, I mean any screenshot?

**Comment by tiltmaster** [comment]
> can you specify the error, I mean any screenshot?

If you try to apply any color filter and or add text, an error will appear, the loading will be infinite, the error is : 

```
E/System  ( 8392): Uncaught exception thrown by finalizer
E/System  ( 8392): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda0@6cff93b rejected from java.util.concurrent.ThreadPoolExecutor@31f4858[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
E/System  ( 8392):     at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
E/System  ( 8392):     at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
E/System  ( 8392):     at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
E/System  ( 8392):     at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:678)
E/System  ( 8392):     at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  ( 8392):     at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:588)
E/System  ( 8392):     at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:894)
E/System  ( 8392):     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
E/System  ( 8392):     at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
E/System  ( 8392):     at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
E/System  ( 8392):     at java.lang.Daemons$Daemon.run(Daemons.java:145)
E/System  ( 8392):     at java.lang.Thread.run(Thread.java:1012)
```

which is related to the native code, as when i did not have the native code of the editor which may be using something extremely outdated and or there is a loop within it., it was giving an error of missing channel which was also not identified in the documentation.

**Comment by hamzasidd3634** [comment]
This bug has been fixed in new update, if you have further queries please reopen the issue.
Thanks for using this package
